-- MySQL Schema File
-- This file will be automatically generated by the 'scripts/initialize_db.php'
-- script when DB_TYPE is set to 'mysql' in the configuration and the
-- setup script (setup.sh) is executed successfully.

-- It contains the CREATE TABLE statements for the MySQL database.
-- You can use this file for reference or manual database setup if needed.

